POST https://api-video-manager-vyb3.onrender.com/videos
Content-Type: application/json

{
  "title": "video node",
  "description": "Esse é um video que tem alguma descriçao",
  "duration": 180
}

###

GET https://api-video-manager-vyb3.onrender.com/videos

### 
PUT https://api-video-manager-vyb3.onrender.com/videos/89090f65-759b-41e0-a7c9-3694b97a6a48
Content-Type: application/json

{
  "title": "video teste",
  "description": "funcionou",
  "duration": 110
}

### 

DELETE https://api-video-manager-vyb3.onrender.com/videos/5dd2dce4-11c7-4da3-9590-69b23d7bee66